{% set name = "docker-compose" %}
{% set version = "2.37.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/docker/compose/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b5b21d1886f41cdefe6f4f089503047b60c3f66322b7130636b54f5ccf374441

build:
  number: 0
  script:
    - pushd cmd
    - go install -v .  # [win]
    - move %PREFIX%\bin\cmd.exe %LIBRARY_PREFIX%\bin\docker-compose.exe  # [win]
    - go build -ldflags "-s -w -X github.com/docker/compose/v2/internal.Version=${PKG_VERSION}" -o $PREFIX/bin/docker-compose  # [unix]
    - go-licenses save --save_path ../licenses .
    # Clear out cache to avoid file not removable warnings
    - chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)  # [unix]

requirements:
  build:
    - {{ stdlib('c') }}           # [osx]
    - {{ compiler('c') }}         # [osx]
    - {{ compiler('go-cgo') }}    # [osx]
    - {{ compiler('go-nocgo') }}  # [not osx]
    - go-licenses

test:
  commands:
    - docker-compose --help
    - docker-compose version

about:
  home: https://www.docker.com/
  dev_url: https://github.com/docker/compose
  license: Apache-2.0
  license_file:
    - LICENSE
    - licenses/
  summary: Define and run multi-container applications with Docker
  description: |
    Docker Compose is a tool for running multi-container applications
    on Docker defined using the Compose file format.
    A Compose file is used to define how one or more containers that
    make up your application are configured. Once you have a Compose
    file, you can create and start your application with a single command:
    docker compose up.

extra:
  recipe-maintainers:
    - scopatz
    - xhochy
