{% set name = "docker-compose" %}
{% set version = "1.29.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/docker-compose-{{ version }}.tar.gz
  sha256: 4c8cd9d21d237412793d18bd33110049ee9af8dab3fe2c213bbd0733959b09b7

build:
  entry_points:
    - docker-compose=compose.cli.main:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - docopt >=0.6.1,<1
    - pyyaml >=3.10,<6
    - requests >=2.20.0,<3
    - texttable >=0.9.0,<2
    - websocket-client >=0.32.0,<1
    - distro >=1.5.0,<2
    - docker-py >=5
    - dockerpty >=0.4.1,<1
    - jsonschema >=2.5.1,<4
    - python-dotenv >=0.13.0,<1
    - cached-property <2,>=1.2.0  # [py<38]
    - colorama <1,>=0.4  # [win]

test:
  imports:
    - compose
  commands:
    - pip check
    - docker-compose --help
  requires:
    - pip

about:
  home: https://www.docker.com/
  dev_url: https://github.com/docker/compose
  license: Apache-2.0
  license_file: LICENSE
  summary: Compose is a tool for defining and running multi-container Docker applications.
  description: |
    Compose is a tool for defining and running multi-container Docker
    applications. With Compose, you use a Compose file to configure your
    application's services. Then, using a single command, you create and
    start all the services from your configuration.

extra:
  recipe-maintainers:
    - scopatz
