{% set name = "docker-compose" %}
{% set version = "2.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/docker/compose/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0014b23382a50c90f91849e491500568366052882e22011822ca2d8a3b2976f2

build:
  number: 0
  script:
    - export BUILD_FLAGS="-buildvcs=false"                         # [unix]
    - export DESTDIR="${PREFIX}/libexec/docker/cli-plugins"        # [unix]
    - set BUILD_FLAGS=-buildvcs=false                              # [win]
    - set DESTDIR=%PREFIX%\libexec\docker\cli-plugins              # [win]
    - make

requirements:
  build:
    - {{ compiler('go') }}
    - make

test:
  commands:
    - docker-compose --help
    - docker-compose version

about:
  home: https://www.docker.com/
  dev_url: https://github.com/docker/compose
  license: Apache-2.0
  license_file: LICENSE
  summary: Compose is a tool for defining and running multi-container Docker applications.
  description: |
    Compose is a tool for defining and running multi-container Docker
    applications. With Compose, you use a Compose file to configure your
    application's services. Then, using a single command, you create and
    start all the services from your configuration.

extra:
  recipe-maintainers:
    - scopatz
