{% set name = "docker-compose" %}
{% set version = "1.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e836102d139aca667d6af53f0f4d942c9459ec24d6dd4f0203d74359b0fd311

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - docker-compose = compose.cli.main:main
  # pypiwin32 dependency not yet available on conda-forge
  # dependencies not satisfiable for python v3.5
  skip: true  # [win or py < 36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - ssl_match_hostname ==3.5.0.1  # [py2k]
    - cached-property
    - certifi
    - chardet
    - distro
    - docker-py
    - docker-pycreds
    - dockerpty
    - docopt
    - enum34  # [py2k]
    - functools32  # [py2k]
    - colorama  # [win]
    - idna
    - ipaddress  # [py2k]
    - jsonschema
    # - pypiwin32   # [win]
    - pysocks
    - python-dotenv
    - pyyaml
    - requests
    - pysocks
    - six
    - texttable
    - urllib3
    - websocket-client

test:
  commands:
    - docker-compose --help

about:
  home: https://www.docker.com/
  license: Apache v2.0
  license_family: Apache
  license_file: LICENSE
  summary: Compose is a tool for defining and running multi-container Docker applications.
  description: |
    Compose is a tool for defining and running multi-container Docker
    applications. With Compose, you use a Compose file to configure your
    application's services. Then, using a single command, you create and
    start all the services from your configuration.

extra:
  recipe-maintainers:
    - scopatz
