# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ygiwmWWJoXtuSfrhuv3d4TQhuUek/AzW8Gc7MI+1CLpd2mZe4RPCPBT29AE8u1bczbJxbQPk+Thz4/QlG8D1X1jlnfU708Trg8nyzQnCdAds8zlJ877lRj071es+2U32uCMp19B6QWl4nwMGneXy3nTDXu5jbj/CEk5uZErS6GPpM73tJL9/IcUFc9nJ+mi179e41v7Wzf5ZZJrvao1dsNfCrCEx80psWyB79v26oQ452oPaLaLmdDWEJqKkqE7GLxV+HKHpGsyBrntRDAX/qHdYfwxOsg2nFyCJOx4fsPh9UBBMXV54YildFH83SrLk5FUtN8a3SJTsyWNlV+TrVRSXuZIOnlIFWn/XrxXLteZiudtPUHYWiFAVOOLImegWc0jJF/Kd78oeMAsnJOc9DF+lgj7J0/zDwxHsMVAAczufIL3bD1RKdalrZ50HITBKkOzrqyP71MMGYwr0VIA00vcKSDKBEx2CUR4CtyIOmP7yiuKL83XDyykL2aCJjV+wwLHgSoLhzkYvMWaMB+BQEaOcWRTyFxZcng20uxr0MKu/rNsVOdkCkCN8NWMGJWNaRx5yyunYWKPgZN2sD35aCZn5bia6RdYPZlnaECQJPxLi1GCiOZ9MNq/irWk9bLBLUwnYoWT0aahTnJN18b2M3dPzPV2zSphzRDAsTOjvBVQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
